### ISSUE TITLE
Nexus 3.0

### ISSUE THREAD

**Issue by itsfolf** [juliogonzalez/sonatype-nexus-openshift#2]
When will be this updated?

**Comment by juliogonzalez** [comment]
Hi @checkplys,

I'll try to have a look ASAP (maybe this next weekend).

However be warned that maybe it won't work on the free small gears (512MB of RAM).

I also maintain Nexus on RPM format, and I saw that 2.x runs on instances with 512MB while 3.x requires more RAM.

**Comment by juliogonzalez** [comment]
@checkplys, I uploaded today a [new branch nexus3](https://github.com/juliogonzalez/sonatype-nexus-openshift/tree/nexus3) and was able to deploy Nexus 3 and load the web interface.

You can give it a try if you like (let me know if you find issues), but keep in mind that this is not production ready at this moment, as there're some tests I still need to run.

Besides that:
- I still didn't modify my doc on how to deploy nexus3.x
- It's highly possible that I decide to create a new repo for nexus 3.x, as most probably there will be more 2.x releases, and besites that there's no way to migrate from nexus 2.x to nexus 3.x

**Comment by juliogonzalez** [comment]
Please do not deploy this to any production environment, as if I decide to move to another repository you could be unable to upgrade any deployed cartridge..

I will end working on this during the next week.

**Comment by juliogonzalez** [comment]
I finally decided to follow the same approach that Sonatype team is using ([same repository with branches](https://github.com/sonatype/nexus-public/)):
- **[master](https://github.com/juliogonzalez/sonatype-nexus-openshift/tree/master)** branch will contain current history with previous 2.x versions and future 3.x versions
- **[nexus-2.x](https://github.com/juliogonzalez/sonatype-nexus-openshift/tree/nexus-2.x)** branch will contain current history with previous 2.x versions and future 2.x versions

I also added separate Jenkins Jobs to check any new commits to the branches and ensure that I'm not breaking anything.

Temporary nexus3 branch is now deleted, so if you want to deploy Nexus 3.x to a production cartridge, please user master branch (don't upgrade existing cartridges as I was amending nexus3 branch!)

I'll close the issue as it is solved, but feel free to send more feedback if there are any problems.
