### ISSUE TITLE
Doubt about 3.0

### ISSUE THREAD

**Issue by itsfolf** [juliogonzalez/sonatype-nexus-openshift#3]
You said that 3.0 will not run in free (512mb) gears, but nothing is mentioned in the main page, so IDK if you can or not.

**Comment by itsfolf** [comment]
I got it working fine on free gear.
PS: 3.0 is beautiful :O

**Comment by juliogonzalez** [comment]
With the default Nexus 3 memory config, it's not possible to use it with only 512MB.

The good thing is that it wasn't hard to adapt the deploy script so JVM memory usage is configured according to the gear memory size.

However I can't tell you how performance will be under moderate load as I'm not (yet) a Nexus 3 user.

If you manage to test it with moderate/high load and 512MB, let me know about the results :-)

**Comment by itsfolf** [comment]
Is there any way to change the title and images, like, change the loading background, the title ("Nexus Repository Manager") and other things?

**Comment by checkplys** [comment]
I just bugged the FTP and can't locate thigs, can you help, I can even go to..
![image](https://cloud.githubusercontent.com/assets/9268058/15985438/bf2be3f8-2fe4-11e6-86d9-835d344b9a97.png)

**Comment by itsfolf** [comment]
Where can I upload artifacts in 3.0?

**Comment by juliogonzalez** [comment]
Sorry @checkplys, I only packaged Nexus 3.0.0-03 for Openshift (and as RPM), but I still didn't start using it). You should have a look at the [nexus 3 manual](https://books.sonatype.com/nexus-book/3.0/reference/install.html).

Regarding changing title, images and graphical attributes, I don't know how to do it for neither Nexus 2 or 3. Maybe you should check at their [support service](https://support.sonatype.com/hc/en-us).

**Comment by checkplys** [comment]
The manual only says where to see info and things. Nothing about adding a fucking artifact.
